// Asteroids, vector version: everything drawn with 1 px lines, like the 1979 arcade machine.
// All the gameplay, sound and controls live in the shared AsteroidsApp; this file only draws the
// world.

#include <cmath>
#include <utility>

#include "AsteroidsApp.h"
#include "Playfield.h"

namespace {

using namespace Asteroids;

const Vec4 kShipColor{0.95f, 0.97f, 1.0f, 1.0f};
const Vec4 kAsteroidColor{0.78f, 0.83f, 0.9f, 1.0f};
const Vec4 kBulletColor{1.0f, 1.0f, 1.0f, 1.0f};
const Vec4 kSaucerColor{0.95f, 0.97f, 1.0f, 1.0f};

class VectorAsteroids final : public AsteroidsApp {
public:
    using AsteroidsApp::AsteroidsApp;

protected:
    void DrawWorld(Emerald::Renderer2D& r) override
    {
        const Game& game = GetGame();

        // Once the game is over the rocks keep drifting, dimmed so the text stays readable.
        Vec4 asteroidColor = kAsteroidColor;
        if (game.IsGameOver())
            asteroidColor.w = 0.35f;
        for (const Asteroid& asteroid : game.GetAsteroids()) {
            ForEachWrappedCopy(asteroid.Position, asteroid.Radius * 1.2f,
                               [&](const Vec2& p) { asteroid.Draw(r, p, asteroidColor); });
        }

        for (const Bullet& bullet : game.GetBullets())
            r.DrawCircle(bullet.Position, 1.5f, kBulletColor, 4);
        for (const Bullet& bullet : game.GetSaucerBullets())
            r.DrawCircle(bullet.Position, 1.5f, kBulletColor, 4);
        if (game.GetSaucer())
            game.GetSaucer()->Draw(r, kSaucerColor);

        for (const Particle& p : game.GetParticles()) {
            const f32 fade = p.TimeLeft / p.Lifetime; // 1 -> 0
            const Vec4 color{1.0f, 1.0f, 1.0f, fade};
            if (p.Length > 0.0f) {
                const Vec2 half = Vec2(std::cos(p.Angle), std::sin(p.Angle)) * (0.5f * p.Length);
                r.DrawLine(p.Position - half, p.Position + half, color);
            } else {
                r.DrawCircle(p.Position, 1.0f, color, 4);
            }
        }

        if (game.IsShipVisible()) {
            const Ship& ship = game.GetShip();
            ForEachWrappedCopy(ship.Position, 20.0f, [&](const Vec2& p) {
                ship.Draw(r, p, kShipColor, game.GetFlameLength());
            });
        }
    }
};

} // namespace

int main(int argc, char** argv)
{
    Options options = ParseOptions(argc, argv);
    Emerald::ApplicationSpec spec = MakeSpec(options, "Asteroids", "logs/Asteroids.log");
    spec.ShaderFormats = EMERALD_SHADER_FORMATS; // formats generated by emerald_add_shaders()

    VectorAsteroids app(spec, std::move(options), "highscores.txt");
    return app.Run();
}
